# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac8d023d30e202ec5a3f73347bf6d0fff8f739f2bbbe3b47e4e0ad73a085cdbf883c3a718ed1d4ced54ca7147c99cb4b261188fc0521e308827e597d6cfbf98
  database_password: budgeter

test:
  secret_key_base: 7dc1a1ac7471f0f4c12fa22f0500024288fe1e10d1ff41d0276b66080e84712d707f41d37b95ce14c9f845cc6bce4abb6677aedf588eee726f949f3dc66d79c4
  database_password: budgeter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
